In [1]:
import numpy as np

In [2]:
mydata = np.arange(0, 20)

In [3]:
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [6]:
np.reshape(mydata, (5, 4)) # Note: Default is opposite to R

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
MATR1 = np.reshape(mydata, (5, 4), order='C')

In [9]:
MATR1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [10]:
# Exercise get to the number 10

In [11]:
MATR1[2, 2]

10

In [12]:
MATR2 = np.reshape(mydata, (5, 4), order='F')

In [13]:
MATR2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [14]:
# Exercise get to the number 17

In [15]:
MATR2[2, 3]

17

In [18]:
# Object Oriented Programming Concept:
# np.reshape(mydata, (5, 4))
# type(mydata) - np.rarray
mydata.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

---

In [19]:
r1 = ["I", "am", "happy"]
r2 = ["What", "a", "day"]
r3 = [1, 2, 3]

In [20]:
[r1, r2, r3]

[['I', 'am', 'happy'], ['What', 'a', 'day'], [1, 2, 3]]

In [21]:
np.array([r1, r2, r3])

array([['I', 'am', 'happy'],
       ['What', 'a', 'day'],
       ['1', '2', '3']], dtype='<U5')

In [22]:
print(np.array([r1, r2, r3]))

[['I' 'am' 'happy']
 ['What' 'a' 'day']
 ['1' '2' '3']]
