In [12]:
l = [23245, 27, 546, 215, -1234]

In [13]:
l

[23245, 27, 546, 215, -1234]

In [14]:
import numpy as np

In [15]:
a = np.array(l)

In [16]:
a

array([23245,    27,   546,   215, -1234])

In [20]:
b = np.array([12, 455, 63.3, True, "a"]) 
# Every item in array must be same

In [21]:
b

array(['12', '455', '63.3', 'True', 'a'], dtype='<U32')

In [22]:
print(b)

['12' '455' '63.3' 'True' 'a']


In [23]:
l.pop()

-1234

In [24]:
l

[23245, 27, 546, 215]

In [25]:
a.mean()

4559.8

In [26]:
b = np.array([12, 455, 63.3, True])

In [27]:
b

array([ 12. , 455. ,  63.3,   1. ])

---

In [28]:
# Array Slicing

In [29]:
a

array([23245,    27,   546,   215, -1234])

In [30]:
a[2:]

array([  546,   215, -1234])

In [31]:
a[2:4]

array([546, 215])

In [32]:
b = a[2:4]

In [33]:
b

array([546, 215])

In [34]:
b[0]

546

In [36]:
b[:] = 111

In [37]:
b

array([111, 111])

In [38]:
a

array([23245,    27,   111,   111, -1234])

In [40]:
c = a.copy()

In [41]:
c

array([23245,    27,   111,   111, -1234])

In [43]:
c[0] = 0

In [44]:
c

array([    0,    27,   111,   111, -1234])

In [45]:
a

array([23245,    27,   111,   111, -1234])